services:
  scraper:
    build: .
    container_name: tower-scraper
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    environment:
      - MCP_TRANSPORT=${MCP_TRANSPORT:-sse}
      - APP_PORT=${APP_PORT}
      - MCP_API_KEY=${MCP_API_KEY}
      - TOWER_API_ACCOUNT=${TOWER_API_ACCOUNT}
      - TOWER_API_KEY=${TOWER_API_KEY}
      - TOWER_MULTICOVERAGE_ID=${TOWER_MULTICOVERAGE_ID:-31710}
      - TOWER_USERNAME=${TOWER_USERNAME}
      - TOWER_PASSWORD=${TOWER_PASSWORD}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_HOST=${DB_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - SWAGGER_ENABLED=${SWAGGER_ENABLED:-true}
      - TOWER_COVERAGE_CONCURRENCY=${TOWER_COVERAGE_CONCURRENCY}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes: #para poder ver los archivos de la aplicacion
      - ./:/app